import {
  createContext,
  useCallback,
  useEffect,
  useReducer,
  useRef,
  type ReactNode,
} from 'react';
import { createEmptyAppData, generateId, type AppData } from '../types';
import { flushSave, loadAppData } from '../storage/storage';
import { classifyActionProvenance, resolveDirtyTargets } from '../sync/actionProvenance';
import { createSyncGeneration, type SyncGeneration } from '../sync/generation';
import {
  clearAllDirty,
  getAccountMetadata,
  markDirty,
  upsertAccountMetadata,
} from '../sync/metadata';
import { loadSyncMetadataStore, saveSyncMetadataStore } from '../sync/metadataStorage';
import { useAuth } from './useAuth';
import { appReducer, type AppAction } from './reducer';

interface AppContextValue {
  state: AppData;
  dispatch: React.Dispatch<AppAction>;
  /**
   * Phase 5B3B — exposed so `SyncEngineContext` can check `isCurrent()`
   * between network operations and stop promptly after sign-out, account
   * switch, RESET, IMPORT, or this provider's own teardown, without ever
   * attempting to cancel a request already sent. See src/sync/generation.ts.
   */
  syncGeneration: SyncGeneration;
}

export const AppContext = createContext<AppContextValue | null>(null);

/**
 * Actions whose id is generated by the reducer internally (a fresh
 * `crypto.randomUUID()`/timestamp) when none is supplied. The dispatch
 * wrapper below pre-generates and injects that id *before* forwarding the
 * action, so the same id is both what gets persisted and what gets marked
 * dirty (see `resolveDirtyTargets`'s doc comment in
 * `src/sync/actionProvenance.ts` for why calling the reducer a second time
 * to "peek" at the created id would be unsafe).
 */
function withPreGeneratedId(action: AppAction): AppAction {
  if (
    (action.type === 'ADD_TASK' || action.type === 'ADD_PROJECT' || action.type === 'UPSERT_DAILY_NOTE') &&
    !action.id
  ) {
    return { ...action, id: generateId() };
  }
  return action;
}

export function AppProvider({ children }: { children: ReactNode }) {
  const [state, rawDispatch] = useReducer(appReducer, createEmptyAppData(), () => loadAppData());
  const auth = useAuth();

  useEffect(() => {
    flushSave(state);
  }, [state]);

  const stateRef = useRef(state);
  stateRef.current = state;

  const accountId = auth.isSupabaseConfigured ? (auth.user?.id ?? null) : null;
  const accountIdRef = useRef(accountId);
  accountIdRef.current = accountId;

  // Phase 5B3A's generation/cancellation scaffold — see src/sync/generation.ts.
  const syncGenerationRef = useRef(createSyncGeneration());
  const previousAccountIdRef = useRef<string | null | undefined>(undefined);

  useEffect(() => {
    // Only invalidate when there *was* an active account whose pending work
    // could now be stale — sign-out (a real account -> null) or switching to
    // a different real account. Deliberately does NOT invalidate on sign-in
    // (undefined-sentinel or null -> a real account): nothing was running
    // for this device while signed out, so there is nothing to protect
    // against, and a drain triggered by this very sign-in (see
    // SyncEngineContext.tsx's effect on the same accountId transition) must
    // not have its own just-captured generation invalidated by the sign-in
    // that started it — these two effects run from the same render.
    if (previousAccountIdRef.current && previousAccountIdRef.current !== accountId) {
      syncGenerationRef.current.invalidate();
    }
    previousAccountIdRef.current = accountId;
  }, [accountId]);

  useEffect(() => {
    const generation = syncGenerationRef.current;
    return () => {
      generation.invalidate();
    };
  }, []);

  const dispatch = useCallback<React.Dispatch<AppAction>>((rawAction) => {
    const action = withPreGeneratedId(rawAction);
    const provenance = classifyActionProvenance(action);

    if (provenance === 'user-edit') {
      const currentAccountId = accountIdRef.current;
      // No-op when signed out: nothing is marked dirty for a device with no
      // authenticated account to attribute the edit to.
      if (currentAccountId) {
        const targets = resolveDirtyTargets(action, stateRef.current);
        if (targets.length > 0) {
          // Durable as of Phase 5B3B: loaded and saved fresh on every
          // dirty-producing dispatch, not held in memory — a refresh or
          // brief offline period must not lose unsynced work. Read-patch-save
          // (never a batch spanning an `await`) so this can never race with
          // the sync engine's own per-record patches to other ids.
          const store = loadSyncMetadataStore();
          let accountMetadata = getAccountMetadata(store, currentAccountId);
          for (const target of targets) {
            accountMetadata = markDirty(accountMetadata, target.entity, target.id);
          }
          saveSyncMetadataStore(upsertAccountMetadata(store, accountMetadata));
        }
      }
    } else if (action.type === 'RESET' || action.type === 'IMPORT') {
      // LOAD and APPLY_REMOTE_UPDATE are also sync-boundary but are not
      // invalidation triggers themselves — see src/sync/generation.ts.
      syncGenerationRef.current.invalidate();

      // RESET/IMPORT wholesale-replace local state, so whatever was
      // previously dirty for the current account no longer corresponds to
      // anything the (new) local state holds — see clearAllDirty's doc
      // comment. Only the *currently authenticated* account's bucket is
      // touched; a different account's pending work is never affected by an
      // action that happens while it isn't the active account (bind-to-
      // account, never cross-account).
      const currentAccountId = accountIdRef.current;
      if (currentAccountId) {
        const store = loadSyncMetadataStore();
        const accountMetadata = clearAllDirty(getAccountMetadata(store, currentAccountId));
        saveSyncMetadataStore(upsertAccountMetadata(store, accountMetadata));
      }
    }

    rawDispatch(action);
  }, []);

  return (
    <AppContext.Provider value={{ state, dispatch, syncGeneration: syncGenerationRef.current }}>
      {children}
    </AppContext.Provider>
  );
}
