import {
  createContext,
  useCallback,
  useEffect,
  useReducer,
  useRef,
  type ReactNode,
} from 'react';
import { createEmptyAppData, generateId, type AppData } from '../types';
import { flushSave, loadAppData } from '../storage/storage';
import { classifyActionProvenance, resolveDirtyTargets } from '../sync/actionProvenance';
import { createSyncGeneration } from '../sync/generation';
import {
  createEmptySyncMetadataStore,
  getAccountMetadata,
  markDirty,
  upsertAccountMetadata,
  type SyncMetadataStore,
} from '../sync/metadata';
import { useAuth } from './useAuth';
import { appReducer, type AppAction } from './reducer';

interface AppContextValue {
  state: AppData;
  dispatch: React.Dispatch<AppAction>;
}

export const AppContext = createContext<AppContextValue | null>(null);

/**
 * Actions whose id is generated by the reducer internally (a fresh
 * `crypto.randomUUID()`/timestamp) when none is supplied. The dispatch
 * wrapper below pre-generates and injects that id *before* forwarding the
 * action, so the same id is both what gets persisted and what gets marked
 * dirty (see `resolveDirtyTargets`'s doc comment in
 * `src/sync/actionProvenance.ts` for why calling the reducer a second time
 * to "peek" at the created id would be unsafe).
 */
function withPreGeneratedId(action: AppAction): AppAction {
  if (
    (action.type === 'ADD_TASK' || action.type === 'ADD_PROJECT' || action.type === 'UPSERT_DAILY_NOTE') &&
    !action.id
  ) {
    return { ...action, id: generateId() };
  }
  return action;
}

export function AppProvider({ children }: { children: ReactNode }) {
  const [state, rawDispatch] = useReducer(appReducer, createEmptyAppData(), () => loadAppData());
  const auth = useAuth();

  useEffect(() => {
    flushSave(state);
  }, [state]);

  const stateRef = useRef(state);
  stateRef.current = state;

  const accountId = auth.isSupabaseConfigured ? (auth.user?.id ?? null) : null;
  const accountIdRef = useRef(accountId);
  accountIdRef.current = accountId;

  // In-memory only for this phase (Phase 5B3A, task 3 of 3) — deliberately
  // never read from or written to `daily-compass-sync-v1` here. It starts
  // empty every session and is never persisted, so it cannot drift from or
  // clobber whatever CloudSyncContext's hydration flow has separately saved
  // there; nothing yet reads this dirty bookkeeping either, so there is
  // nothing to lose by keeping it in-memory-only at this stage.
  const metadataStoreRef = useRef<SyncMetadataStore>(createEmptySyncMetadataStore());

  // Phase 5B3A's generation/cancellation scaffold — see src/sync/generation.ts.
  const syncGenerationRef = useRef(createSyncGeneration());
  const previousAccountIdRef = useRef<string | null | undefined>(undefined);

  useEffect(() => {
    // Skip the very first run (mounting with an already-known account is not
    // a "change") — only an actual transition invalidates the generation.
    if (previousAccountIdRef.current !== undefined && previousAccountIdRef.current !== accountId) {
      syncGenerationRef.current.invalidate();
    }
    previousAccountIdRef.current = accountId;
  }, [accountId]);

  useEffect(() => {
    const generation = syncGenerationRef.current;
    return () => {
      generation.invalidate();
    };
  }, []);

  const dispatch = useCallback<React.Dispatch<AppAction>>((rawAction) => {
    const action = withPreGeneratedId(rawAction);
    const provenance = classifyActionProvenance(action);

    if (provenance === 'user-edit') {
      const currentAccountId = accountIdRef.current;
      // No-op when signed out: nothing is marked dirty for a device with no
      // authenticated account to attribute the edit to.
      if (currentAccountId) {
        const targets = resolveDirtyTargets(action, stateRef.current);
        if (targets.length > 0) {
          let accountMetadata = getAccountMetadata(metadataStoreRef.current, currentAccountId);
          for (const target of targets) {
            accountMetadata = markDirty(accountMetadata, target.entity, target.id);
          }
          metadataStoreRef.current = upsertAccountMetadata(metadataStoreRef.current, accountMetadata);
        }
      }
    } else if (action.type === 'RESET' || action.type === 'IMPORT') {
      // LOAD and APPLY_REMOTE_UPDATE are also sync-boundary but are not
      // invalidation triggers themselves — see src/sync/generation.ts.
      syncGenerationRef.current.invalidate();
    }

    rawDispatch(action);
  }, []);

  return (
    <AppContext.Provider value={{ state, dispatch }}>{children}</AppContext.Provider>
  );
}
